<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RequisitoLegal;

class RequisitoLegalSeeder extends Seeder
{
    public function run(): void
    {
        $hoje = now()->toDateString();

        $requisitos = [
            // ── CEBAS — Geral (todos os eixos) ───────────────────────────────
            [
                'codigo'       => 'CEBAS-G-001',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Estatuto social atualizado',
                'enunciado'    => 'Manter estatuto social registrado em cartório, com finalidade sem fins lucrativos explícita e previsão de destinação do patrimônio em caso de dissolução.',
                'base_legal'   => 'LC 187/2021, art. 3º, I',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-G-002',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'CNPJ ativo e regular',
                'enunciado'    => 'Manter CNPJ ativo junto à Receita Federal, sem pendências de baixa ou suspensão.',
                'base_legal'   => 'LC 187/2021, art. 3º',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-G-003',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Certidão Negativa de Débitos — INSS (CND/INSS)',
                'enunciado'    => 'Manter certidão negativa de débitos previdenciários válida.',
                'base_legal'   => 'LC 187/2021, art. 3º, IV; Lei 8.212/1991',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-G-004',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Certidão de Regularidade Fiscal — FGTS (CRF/FGTS)',
                'enunciado'    => 'Manter CRF válida junto à Caixa Econômica Federal.',
                'base_legal'   => 'LC 187/2021, art. 3º, IV; Lei 8.036/1990',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-G-005',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Certidão Negativa de Débitos Federais',
                'enunciado'    => 'Manter CND federal (Receita Federal + PGFN) válida.',
                'base_legal'   => 'LC 187/2021, art. 3º, IV',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-G-006',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Certidão Negativa de Débitos Estadual',
                'enunciado'    => 'Manter certidão negativa de débitos estaduais válida no estado-sede.',
                'base_legal'   => 'LC 187/2021, art. 3º, IV',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'CEBAS-G-007',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Certidão Negativa de Débitos Municipal',
                'enunciado'    => 'Manter certidão negativa de débitos municipais válida no município-sede.',
                'base_legal'   => 'LC 187/2021, art. 3º, IV',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'CEBAS-G-008',
                'eixo'         => 'cebas_geral',
                'area'         => 'geral',
                'titulo'       => 'Escrituração contábil mensal',
                'enunciado'    => 'Manter escrituração contábil regular, com lançamentos em todos os meses do exercício.',
                'base_legal'   => 'LC 187/2021, art. 3º, III; NBC TG 1000',
                'tipo'         => 'A',
                'periodicidade'=> 'mensal',
                'risco'        => 'alto',
            ],

            // ── CEBAS — Assistência Social ────────────────────────────────────
            [
                'codigo'       => 'CEBAS-AS-001',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Inscrição no CNAS',
                'enunciado'    => 'Manter inscrição válida no Conselho Nacional de Assistência Social (CNAS).',
                'base_legal'   => 'LC 187/2021, art. 18, I; LOAS, art. 9º',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-AS-002',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Percentual mínimo de gratuidade',
                'enunciado'    => 'Comprovar que pelo menos o percentual mínimo regulamentado dos atendimentos são gratuitos, destinados ao público SUAS.',
                'base_legal'   => 'LC 187/2021, art. 18, II; Decreto 8.242/2014',
                'tipo'         => 'A',
                'periodicidade'=> 'anual',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-AS-003',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Inscrição no CMAS',
                'enunciado'    => 'Manter inscrição válida no Conselho Municipal de Assistência Social (CMAS) do município-sede.',
                'base_legal'   => 'LC 187/2021, art. 18; LOAS, art. 9º',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-AS-004',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Registro CNEAS',
                'enunciado'    => 'Manter registro ativo no Cadastro Nacional de Entidades de Assistência Social (CNEAS).',
                'base_legal'   => 'Resolução CNAS 16/2010; LC 187/2021',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-AS-005',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Relatório de atividades anual',
                'enunciado'    => 'Elaborar e manter relatório de atividades do exercício, descrevendo serviços prestados, público atendido e resultados.',
                'base_legal'   => 'LC 187/2021, art. 18, IV',
                'tipo'         => 'C',
                'periodicidade'=> 'anual',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'CEBAS-AS-006',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Balanço patrimonial e DRE',
                'enunciado'    => 'Manter balanço patrimonial e demonstrativo de resultados do exercício (DRE) elaborados por contador habilitado.',
                'base_legal'   => 'LC 187/2021, art. 3º, III',
                'tipo'         => 'B',
                'periodicidade'=> 'anual',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-AS-007',
                'eixo'         => 'cebas_as',
                'area'         => 'as',
                'titulo'       => 'Parecer de auditoria contábil',
                'enunciado'    => 'Obter parecer de auditoria independente para entidades com receita acima do limite regulamentado.',
                'base_legal'   => 'LC 187/2021, art. 3º, III',
                'tipo'         => 'B',
                'periodicidade'=> 'anual',
                'risco'        => 'medio',
            ],

            // ── CEBAS — Saúde ─────────────────────────────────────────────────
            [
                'codigo'       => 'CEBAS-S-001',
                'eixo'         => 'cebas_saude',
                'area'         => 'saude',
                'titulo'       => 'Oferta de serviços ao SUS (mínimo 60%)',
                'enunciado'    => 'Comprovar que pelo menos 60% dos serviços são prestados ao SUS, conforme regulamentação do MS.',
                'base_legal'   => 'LC 187/2021, art. 24',
                'tipo'         => 'C',
                'periodicidade'=> 'anual',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'CEBAS-S-002',
                'eixo'         => 'cebas_saude',
                'area'         => 'saude',
                'titulo'       => 'Licença sanitária vigente',
                'enunciado'    => 'Manter licença de funcionamento emitida pela vigilância sanitária estadual/municipal válida.',
                'base_legal'   => 'LC 187/2021, art. 24; Lei 9.782/1999',
                'tipo'         => 'B',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],

            // ── CEBAS — Educação ──────────────────────────────────────────────
            [
                'codigo'       => 'CEBAS-E-001',
                'eixo'         => 'cebas_educacao',
                'area'         => 'educacao',
                'titulo'       => 'Bolsas de estudo concedidas (mínimo 1:5)',
                'enunciado'    => 'Comprovar concessão de bolsas de estudo na proporção mínima de 1 bolsa integral para cada 5 alunos pagantes.',
                'base_legal'   => 'LC 187/2021, art. 13; Decreto 7.237/2010',
                'tipo'         => 'C',
                'periodicidade'=> 'anual',
                'risco'        => 'alto',
            ],

            // ── MROSC — Lei 13.019/2014 ───────────────────────────────────────
            [
                'codigo'       => 'MROSC-P-001',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Plano de trabalho aprovado',
                'enunciado'    => 'Ter plano de trabalho com objeto, metas, cronograma de execução e previsão de receitas e despesas aprovado pelo órgão concedente.',
                'base_legal'   => 'Lei 13.019/2014, art. 22',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'MROSC-P-002',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Conta bancária exclusiva da parceria',
                'enunciado'    => 'Manter conta bancária específica para movimentação dos recursos da parceria.',
                'base_legal'   => 'Lei 13.019/2014, art. 51',
                'tipo'         => 'C',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'MROSC-P-003',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Relatório de execução parcial (semestral)',
                'enunciado'    => 'Encaminhar ao órgão parceiro relatório de execução financeira e de objeto no prazo semestral.',
                'base_legal'   => 'Lei 13.019/2014, art. 66',
                'tipo'         => 'C',
                'periodicidade'=> 'mensal',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'MROSC-P-004',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Publicação no portal de transparência',
                'enunciado'    => 'Publicar extrato do instrumento, relatórios e prestações de contas no portal de transparência do órgão concedente.',
                'base_legal'   => 'Lei 13.019/2014, art. 11',
                'tipo'         => 'C',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'MROSC-P-005',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Prestação de contas final',
                'enunciado'    => 'Apresentar prestação de contas final no prazo de 90 dias após o término da vigência.',
                'base_legal'   => 'Lei 13.019/2014, art. 69',
                'tipo'         => 'B',
                'periodicidade'=> 'por_ciclo',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'MROSC-P-006',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Comprovantes de despesa elegível',
                'enunciado'    => 'Manter notas fiscais / recibos de todas as despesas realizadas com recursos da parceria.',
                'base_legal'   => 'Lei 13.019/2014, art. 68',
                'tipo'         => 'A',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'MROSC-P-007',
                'eixo'         => 'mrosc',
                'area'         => 'geral',
                'titulo'       => 'Cumprimento de metas do plano de trabalho',
                'enunciado'    => 'Comprovar execução das metas previstas no plano de trabalho com desvio máximo de 25%.',
                'base_legal'   => 'Lei 13.019/2014, art. 49',
                'tipo'         => 'A',
                'periodicidade'=> 'mensal',
                'risco'        => 'alto',
            ],

            // ── SUAS ──────────────────────────────────────────────────────────
            [
                'codigo'       => 'SUAS-OP-001',
                'eixo'         => 'suas',
                'area'         => 'as',
                'titulo'       => 'RMA enviado mensalmente',
                'enunciado'    => 'Encaminhar o Registro Mensal de Atendimentos (RMA) ao órgão gestor do SUAS até o dia 10 do mês subsequente.',
                'base_legal'   => 'Resolução CNAS 13/2014; NOB-SUAS 2012',
                'tipo'         => 'C',
                'periodicidade'=> 'mensal',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'SUAS-OP-002',
                'eixo'         => 'suas',
                'area'         => 'as',
                'titulo'       => 'Atendimentos tipificados no SUAS',
                'enunciado'    => 'Registrar a tipificação SUAS de cada atendimento (PAIF, SCFV, PETI, PAEFI etc.) conforme Resolução CNAS 109/2009.',
                'base_legal'   => 'Resolução CNAS 109/2009; NOB-SUAS 2012',
                'tipo'         => 'A',
                'periodicidade'=> 'continua',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'SUAS-OP-003',
                'eixo'         => 'suas',
                'area'         => 'as',
                'titulo'       => 'Equipe de referência conforme NOB-RH/SUAS',
                'enunciado'    => 'Manter equipe técnica mínima conforme NOB-RH/SUAS 2006: assistente social, psicólogo e educador social.',
                'base_legal'   => 'NOB-RH/SUAS 2006; NOB-SUAS 2012',
                'tipo'         => 'A',
                'periodicidade'=> 'continua',
                'risco'        => 'alto',
            ],
            [
                'codigo'       => 'SUAS-OP-004',
                'eixo'         => 'suas',
                'area'         => 'as',
                'titulo'       => 'Plano de Ação aprovado',
                'enunciado'    => 'Elaborar e ter aprovado pelo CMAS o Plano de Ação anual da entidade no SUAS.',
                'base_legal'   => 'NOB-SUAS 2012, art. 9º',
                'tipo'         => 'C',
                'periodicidade'=> 'anual',
                'risco'        => 'medio',
            ],
            [
                'codigo'       => 'SUAS-OP-005',
                'eixo'         => 'suas',
                'area'         => 'as',
                'titulo'       => 'Monitoramento e avaliação pelo CMAS',
                'enunciado'    => 'Submeter-se ao processo de monitoramento e avaliação periódica pelo Conselho Municipal de Assistência Social.',
                'base_legal'   => 'LOAS, art. 18; NOB-SUAS 2012',
                'tipo'         => 'C',
                'periodicidade'=> 'anual',
                'risco'        => 'baixo',
            ],
        ];

        foreach ($requisitos as $dados) {
            RequisitoLegal::updateOrCreate(
                ['codigo' => $dados['codigo']],
                array_merge($dados, ['vigente_de' => $hoje])
            );
        }
    }
}
